name: Nuget Package Deploy

on: 
 push:
   branches: 
     - main
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.5.3  
    - name: Setup NuGet.exe 
      uses: NuGet/setup-nuget@v1.1.1 
    - name: setup-msbuild
      uses: microsoft/setup-msbuild@v1.3.1
    - name: Nuget Restore
      run:  nuget restore MauiAndroidToolTips\MauiAndroidToolTips.csproj
    - name: Build with dotnet
      run: msbuild MauiAndroidToolTips\MauiAndroidToolTips.csproj -property:Configuration=Release
    - name: Push Package to nuget
      run: dotnet nuget push **/*.nupkg
             --api-key ${{ secrets.nugetapikey }}
             --source https://api.nuget.org/v3/index.json
